### ISSUE TITLE
Measure orbitdb data usage

### ISSUE THREAD

**Issue by oed** [uport-project/3box-pinning-server#3]
@ozlemulusoy commented on [Wed Sep 26 2018](https://github.com/uport-project/3box-js/issues/52)

Acceptance criteria: Provide numbers

---

@oed commented on [Tue Oct 02 2018](https://github.com/uport-project/3box-js/issues/52#issuecomment-426218295)

I think this story is in the wrong repo.

**Comment by c-castillo** [comment]
I did not find a way to do this programatically and/or using the orbitdb cli. Nevertheless, this can be done using bash scripting by measuring the disk size or a particular directory.
I placed a shell script on the home folder of the machine, so to measure it incrementally it is only needed to run (right now the db size is 2.9M)

[machine-user@machine-user ~]$ ./orbitdb_size
2.9M	/path/to/orbitdb/

**Comment by oed** [comment]
@c-castillo could we create a crontab for this so it's done maybe once a day? (at least) It would also be nice to have a way of visualizing the data. Maybe we should create new stories for these two tasks?
