### ISSUE TITLE
Create a dashboard with a time series of the orbitdb storage size

### ISSUE THREAD

**Issue by ozlemulusoy** [uport-project/3box-pinning-server#5]

**Comment by oed** [comment]
we should probably also check the size of the ipfs folder!

**Comment by c-castillo** [comment]
`http://ipfs.3box.io:9090/graph?g0.range_input=1h&g0.expr=node_directory_size_mbytes%7Bdirectory%3D%22%2Fopt%2Forbitdb%22%7D&g0.tab=0`

**Comment by c-castillo** [comment]
@michaelsena @oed see the link above

**Comment by oed** [comment]
Nice! CAn we do a similar one for the ipfs folder? Or can we have both in one view?

**Comment by c-castillo** [comment]
@oed we can have both. I'll add it

**Comment by c-castillo** [comment]
@oed IPFS directory added:
http://ipfs.3box.io:9090/graph?g0.range_input=1d&g0.expr=node_directory_size_mbytes&g0.tab=0

**Comment by oed** [comment]
Perfect 👌🏻
